### ISSUE TITLE
Can this database be used in an async context?

### ISSUE THREAD

**Issue by Frederik-Baetens** [khonsulabs/nebari#30]
Do nebari write operations block? Is there a way to use this database in async projects without wrapping everything in block_on?

**Comment by ecton** [comment]
Nebari blocks when invoked. [BonsaiDb](https://github.com/khonsulabs/bonsaidb/) is our async database implementation that sits atop Nebari.

**Comment by ecton** [comment]
I've updated the readme and crate docs to be explicit about this.

Nebari started as an async-native implementation, but the [overhead of the async task handling](https://community.khonsulabs.com/t/implementing-a-new-storage-layer-for-bonsaidb/78/4#async-isnt-worth-it-for-my-usage-pattern-5) was too much for the inner workings of the implementation.

Thank you for checking the project out, and sorry if this answer leaves you still looking for a database for your needs. I would encourage you to check out BonsaiDb -- while it's a different design, it is designed for async from the start.

**Comment by Frederik-Baetens** [comment]
Thanks a lot for your answer! I was looking around for an embedded database to use in my own distributed key value database, and liked that nebari provides the serialization for me, whereas I currently need to worry about serialization myself when using Sled. I'll definitly have a look at bonsaiDB as well if I ever outgrow Sled.

Anyways, I have a lot of respect for the impressive databases you're building. Have a wonderful day!
